"""ubah tabel user sama session

Revision ID: 1738c012b3c5
Revises: 3773da7af4a7
Create Date: 2026-05-26 13:23:35.161577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1738c012b3c5'
# down_revision: Union[str, Sequence[str], None] = '3773da7af4a7'
down_revision: Union[str, Sequence[str], None] = '4e2b9c1a7d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facility_admins')
    op.drop_table('super_admins')
    op.drop_table('civitas')
    op.add_column('user_sessions', sa.Column('refresh_token_hash', sa.String(), nullable=False))
    op.add_column('user_sessions', sa.Column('ip_address', sa.String(), nullable=True))
    op.add_column('user_sessions', sa.Column('user_agent', sa.Text(), nullable=True))
    op.add_column('user_sessions', sa.Column('is_revoked', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('user_sessions', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_sessions', sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_sessions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_sessions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.alter_column('user_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_session_token'), table_name='user_sessions')
    op.drop_column('user_sessions', 'session_token')
    op.drop_column('user_sessions', 'refresh_token')
    op.add_column('users', sa.Column('work_unit', sa.String(), nullable=True))
    op.add_column('users', sa.Column('authority_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('last_failed_login_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    userroles_enum = sa.Enum(
        'admin',
        'civitas',
        'facility_manager',
        name='userroles'
    )
    userroles_enum.create(op.get_bind(), checkfirst=True)

    # op.alter_column('users', 'role',
    #            existing_type=sa.VARCHAR(),
    #            type_=userroles_enum,
    #            existing_nullable=False)
    
    op.execute(
        """
        ALTER TABLE users
        ALTER COLUMN role TYPE userroles
        USING role::userroles
        """
    )
    op.create_index(
        'ix_user_sessions_refresh_token_hash',
        'user_sessions',
        ['refresh_token_hash'],
        unique=True
    )
    op.create_index(
        'ix_user_sessions_user_id',
        'user_sessions',
        ['user_id']
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'civitas', 'facility_manager', name='userroles'),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'last_failed_login_at')
    op.drop_column('users', 'locked_until')
    op.drop_column('users', 'failed_login_attempts')
    op.drop_column('users', 'authority_code')
    op.drop_column('users', 'work_unit')
    op.add_column('user_sessions', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_sessions', sa.Column('session_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.alter_column('user_sessions', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_sessions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user_sessions', 'deleted_at')
    op.drop_column('user_sessions', 'last_used_at')
    op.drop_column('user_sessions', 'revoked_at')
    op.drop_column('user_sessions', 'is_revoked')
    op.drop_column('user_sessions', 'user_agent')
    op.drop_column('user_sessions', 'ip_address')
    op.drop_column('user_sessions', 'refresh_token_hash')
    op.create_table('civitas',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('civitas_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('civitas_pkey'))
    )
    op.create_table('super_admins',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('authority_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('super_admins_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('super_admins_pkey'))
    )
    op.create_table('facility_admins',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('work_unit', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name=op.f('facility_admins_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('facility_admins_pkey'))
    )
    # ### end Alembic commands ###
