"""add handover fields to bookings

Revision ID: d7a872011525
Revises: cd5a829500aa
Create Date: 2026-05-14 13:09:25.402096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a872011525'
down_revision: Union[str, Sequence[str], None] = 'cd5a829500aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('handover_token', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('handover_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_bookings_handover_token'), 'bookings', ['handover_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_handover_token'), table_name='bookings')
    op.drop_column('bookings', 'handover_expires_at')
    op.drop_column('bookings', 'handover_token')
    # ### end Alembic commands ###
